// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb3TQ5STKHj81VBAr1_5y0TgmhQCMF0wg',
    appId: '1:522096883862:web:81ad439ca58de2a73d2ab7',
    messagingSenderId: '522096883862',
    projectId: 'notification-f2dc9',
    authDomain: 'notification-f2dc9.firebaseapp.com',
    storageBucket: 'notification-f2dc9.appspot.com',
    measurementId: 'G-FSJ1J75N2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3y1EB00w5A6qPyEzS3bfpiRrOk4Z1qBM',
    appId: '1:522096883862:android:a1df278143c816183d2ab7',
    messagingSenderId: '522096883862',
    projectId: 'notification-f2dc9',
    storageBucket: 'notification-f2dc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAlRB36BaT0W1qf8FlFHPIfElXMSyudA0',
    appId: '1:522096883862:ios:bb3c64ff25cfed4b3d2ab7',
    messagingSenderId: '522096883862',
    projectId: 'notification-f2dc9',
    storageBucket: 'notification-f2dc9.appspot.com',
    iosClientId: '522096883862-1sq14lbd3l24q13ps2ehdu215fmqfk8o.apps.googleusercontent.com',
    iosBundleId: 'com.insta.instagram',
  );
}
